[package]
name = "slasher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bindings = { path = "../bindings", package = "foundry-contracts" }
dotenv = "0.15.0"
env_logger = "0.11.3"
ethers = { version = "2", features = ["rustls"] }
kalypso_helper = {path = "../helper", package = "helper"}
log = "0.4"
matching_engine_helpers = { path = "../matching_engine", package = "matching_engine" }
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.178", features = ["derive"] }
serde_json = "1.0.104"
tokio = { version = "1.15.0", features = ["full"] }

[features]
default = []
force_transactions = []