[workspace]
members = [
    "bindings",
    "helper",
    "listener", 
    "matching_engine",
    "matching_engine_client",
    "ivs", 
    "ivs_client",
    "generator", 
    "generator_client",
    "integration_checks",
    "kalypso-cli",
    "slasher", 
    "binding_patches",
]
resolver = "2"

[profile.dev]
panic = "abort"
debug = true

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
