[workspace]
members = [
    "bindings",
    "helper",
    "listener", 
    "matching_engine",
    "matching_engine_client",
    "ivs", 
    "ivs_client",
    "generator", 
    "generator_client",
    "integration_checks",
]
