[package]
name = "kalypso-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.64" 
bytes = "1.0"
bindings = { path = "../bindings", package = "foundry-contracts" }
dotenv = "0.15.0"
dialoguer = "0.10.3"
ethers = { version = "2", features = ["rustls"] }
env_logger = "0.11"
flate2 = "1.0.28"
futures = "0.3"
generator_client = {path = "../generator_client", package = "generator_client"}
generator = {path = "../generator", package = "generator"}
hex = "0.4.3"
kalypso_helper = {path = "../helper", package = "helper"}
log = "0.4"
matching_engine_helpers = { path = "../matching_engine", package = "matching_engine" }
openssl = { version = "0.10.57", features = ["vendored"] }
reqwest = { version = "0.11", features = ["stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.10"
tokio = { version = "1.15.0", features = ["full"] }
url = "2.3.1"