[package]
name = "matching_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = {version = "4.5.1", features = ["rustls"] }
anyhow = "1.0.86"
bindings = { path = "../bindings", package = "foundry-contracts" }
dotenv = "0.15.0"
ecies = {version = "0.2.6", features = ["std"]}
env_logger = "0.11.3"
ethers = { version = "2", features = ["rustls"] }
eyre = "0.6"
flate2 = "1.0.28"
futures-util = "0.3.28"
hex = "0.4.3"
im = { version = "15.1.0", features = ["serde"] }
kalypso_helper = {path = "../helper", package = "helper"}
lazy_static = "1.4.0"
log = "0.4"
once_cell = "1.20.2"
rayon = "1.10.0"
reqwest = { version = "0.12.4", features = ["json"] }
secp256k1 = "0.30.0"
serde = { version = "1.0.178", features = ["derive"] }
serde_json = "1.0.104"
service_check_helper = {path = "../generator", package = "generator"}
tokio = { version = "1.15.0", features = ["full"] }
utoipa = "5"
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }

[features]
# inside enclaves
default = ["beta"]
beta = []
stagenet = ["complete"]

# outside enclave
external_indexer = ["complete", "disable_match_creation"]

# Mode Features
complete = [
    "matching_engine_enable_cors",
    "skip_unknown_events",
    "override_symbiotic_slashing_to_zero",
    "override_native_slashing_to_zero",
    "generate_dummy_slash_logs",
    "l1_info",
]

# Sub-Features
l1_info = [
    "use_l1_block_numbers",
    "add_timestamp_to_asks",
]
matching_engine_enable_cors = ["kalypso_helper/enable_cors"]

# Independent Features
add_timestamp_to_asks = [] # Adds timestamp to asks, for better fields in UI
disable_match_creation = [] # Stops creating matches, useful when running outside enclave
override_native_slashing_to_zero = [] # Overrides the slashing amount to 0, in internal records
override_symbiotic_slashing_to_zero = [] # Overrides the slashing amount to 0, in internal records
force_transactions = [] # Forces transaction made on chain by avoid revert checks and manually overriding gas limit
skip_unknown_events = [] # Skips if any known event occurs, userful when contract updates happen
use_l1_block_numbers = [] # Uses L1 block number in internal indexer. Doesn't not effect matching
generate_dummy_slash_logs = [] # Populates internal record with slashing records as if instant slashing was enabled done by stake manager. Doesn't effect matching
