#![allow(clippy::all)]
#![allow(warnings)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod access_control_upgradeable;
pub mod address;
pub mod attestation_auther_upgradeable;
pub mod binding_generator;
pub mod context_upgradeable;
pub mod ecdsa;
pub mod entity_key_registry;
pub mod enumerable_set;
pub mod erc165_upgradeable;
pub mod erc1967_utils;
pub mod error;
pub mod errors;
pub mod generator_registry;
pub mod helper;
pub mod i_access_control;
pub mod i_attestation_verifier;
pub mod i_beacon;
pub mod i_generator_callbacks;
pub mod i_generator_registry;
pub mod i_native_staking;
pub mod i_proof_marketplace;
pub mod i_reward_distributor;
pub mod i_staking_manager;
pub mod i_staking_pool;
pub mod i_symbiotic_staking;
pub mod i_symbiotic_staking_reward;
pub mod i_verifier;
pub mod ierc1363;
pub mod ierc165;
pub mod ierc1822_proxiable;
pub mod ierc1967;
pub mod ierc20;
pub mod initializable;
pub mod math;
pub mod message_hash_utils;
pub mod native_staking;
pub mod panic;
pub mod pausable_upgradeable;
pub mod proof_marketplace;
pub mod reentrancy_guard_upgradeable;
pub mod safe_cast;
pub mod safe_erc20;
pub mod shared_types;
pub mod signed_math;
pub mod staking_manager;
pub mod storage_slot;
pub mod strings;
pub mod struct_;
pub mod symbiotic_staking;
pub mod uups_upgradeable;
