#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod access_control_upgradeable;
pub mod address;
pub mod attestation_auther_upgradeable;
pub mod bindgin_matching_engine;
pub mod context_upgradeable;
pub mod ecdsa;
pub mod entity_key_registry;
pub mod erc165_upgradeable;
pub mod erc1967_utils;
pub mod error;
pub mod generator_registry;
pub mod helper;
pub mod i_access_control;
pub mod i_attestation_verifier;
pub mod i_beacon;
pub mod i_verifier;
pub mod ierc165;
pub mod ierc1822_proxiable;
pub mod ierc20;
pub mod ierc20_permit;
pub mod il2_staking;
pub mod initializable;
pub mod pausable_upgradeable;
pub mod proof_marketplace;
pub mod reentrancy_guard_upgradeable;
pub mod safe_erc20;
pub mod shared_types;
pub mod storage_slot;
pub mod uups_upgradeable;
